### ISSUE TITLE
[Help Wanted] Problems with Mass Extinction Estimation Tutorial in RevBayes Development Version on Intel Mac

### ISSUE THREAD

**Issue by minghao-du** [revbayes/revbayes#421]
Dear RevBayes Developers,

I have attempted to run the Mass Extinction Estimation tutorial from the RevBayes Tutorials but encountered an error message:
`Error: The age of tip 'Acynodon_adriaticus' in the initial tree is outside of specified bounds.`

When I replace the command in the tutorial
`taxa <- readTaxonData("data/crocs_taxa.txt", delim=TAB)`
with
`taxa <- T.taxa()`
the program runs correctly. For details, you can refer to my previous inquiry on the forum at https://groups.google.com/g/revbayes-users/c/shztH9ovxcs.

I compared the Age of Acynodon_adriaticus using both methods and found it to be 75.4715 in each case, so I am unsure why running `taxa <- readTaxonData("data/crocs_taxa.txt", delim=TAB)` results in an error.

I am using the development version of RevBayes, running it on an Intel version of Mac.

Thank you for your assistance.

Best,
Minghao

**Comment by davidcerny** [comment]
Hi Minghao,

It was me who [added this warning](https://github.com/revbayes/revbayes/pull/386) to the development branch last October. It was supposed to have a rather narrow use case: if (1) you want to estimate a tree that includes fossils, (2) the ages of those fossils are read in from a taxon data file, and (3) you want to initialize your analysis with a user-specified tree, then the tip ages of that initial tree indeed have to be within the age ranges listed in the taxon file.

In the [Mass Extinction Estimation tutorial](https://revbayes.github.io/tutorials/divrate/efbdp_me.html), this is not really the case: the tree (`crocs_T1.tre`) is fixed (treated as data) rather than estimated, and the taxon data file (`crocs_taxa.txt`) lists point ages rather than ranges. Moreover, as you point out, these point ages are identical to the tip ages in the tree – and therefore redundant with respect to the latter. This part of the tutorial was intended to teach the users general best practices when it comes to handling fossils in RevBayes, but ironically, these are perhaps not the best in this particular situation. For now, you can feel free to go ahead and change

```
taxa <- readTaxonData("data/crocs_taxa.txt", delim=TAB)
```

to

```
taxa <- T.taxa()
```

as you were advised; it doesn't really change what the analysis is doing in any way. A more permanent solution would be to edit the tutorial itself, so that instead of stating:

> When the tree has fossils, it is best to read in the taxa from a taxon data file. This is absolutely required if the tree is to be simultaneously inferred.

it says something like:

> Here, we extract the fossil ages directly from the tree. If we were to simultaneously infer the tree instead, these ages would have to be read in from a taxon data file.

What do you think @afmagee @hoehna?

**Comment by mhDu** [comment]
Hi David,

Thank you very much for your detailed explanation. It now makes perfect sense why I was encountering the issue with the initial tree's tip ages.

Best,
Minghao

**Comment by bjoelle** [comment]
@davidcerny I am OK with the change to the tutorial, but I still don't see why using a taxon file with ages that are correct should result in an error (even if it's redundant) ?

**Comment by davidcerny** [comment]
It's basically a problem with comparing floats – the ages in the taxon file are not (recognized to be) exactly identical to the ages of the corresponding tips in the tree. As a result, the tree will fail the check in the `startingTreeInitializer()` function that tests for congruence between the two.

**Comment by bjoelle** [comment]
should we make the comparison with a rounding then ? otherwise that problem could happen again in other circumstances

**Comment by davidcerny** [comment]
Maybe! I was thinking of doing that but it seemed like a hacky solution that didn't need to be there in the first place. But I guess one could say the current code is too aggressive about requiring age ranges, and doesn't play nice with fixed ages.

**Comment by davidcerny** [comment]
Fixed by PR #455.
