### ISSUE TITLE
[BUG] Unable to compute probability for fbd_tree in v. 1.2.2

### ISSUE THREAD

**Issue by ZGriebenow** [revbayes/revbayes#477]
I am attempting to run an FBD analysis in v. 1.2.2 (docker) on Ubuntu Linux 20.04, and am encountering an error in which a starting state with a computable probability for a given node cannot be found after 1000 tries.

This occurs for the fbd-tree variable when I use a backbone topology. Conversely, when a backbone topology is not implemented, the probability of the starting state is not computable with respect to the uniform random variable that accounts for fossil stratigraphic range. Since v. 1.2.3 is not yet available on Docker with an Ubuntu-compatible architecture, I have not yet assessed whether this bug occurs in that version.

I have successfully run mcmc_CEFBDP_Specimens.Rev under the same conditions, but consultation with another user and repeated mention of this same error on the RevBayes Google group suggests that this is indeed a difficult-to-replicate bug, rather than the result of misspecifications within my data or script. Hopefully, I am correct in that supposition.

Regards, Zach

[bug-report_122_docker.zip](https://github.com/user-attachments/files/15539482/bug-report_122_docker.zip)

**Comment by davidcerny** [comment]
Based on my own experience, my guess would indeed be that this is due to one of the FBD-related issues that got fixed in v1.2.3 – in some ways, the v1.2.2 release really was uniquely bad when it comes to FBD. (See in particular issues #159, #354, and their respective fixes in PRs #453, #386, both of which occurred between v1.2.2 and v1.2.3.) Often, these MCMC initialization problems are most easily overcome by supplying your own starting tree, but in v1.2.2, it was impossible to have a starting tree and stratigraphic ranges at the same time.

Is there any chance you might be able to run v1.2.3 on Ubuntu outside of Docker?

**Comment by davidcerny** [comment]
@ZGriebenow Unfortunately, I'm unable to reproduce this, because the zipped folder does not contain the `clade_constraints` directory that is referenced in both of your scripts. Could you please provide the constraints as well, just to check if this issue still occurs in the latest release (v1.2.4)?

**Comment by ZGriebenow** [comment]
@davidcerny My apologies; I am attaching the folder containing the necessary text files (and many others).
[clade_constraints.zip](https://github.com/user-attachments/files/15877461/clade_constraints.zip)

**Comment by davidcerny** [comment]
Hi @ZGriebenow, apologies for the late reply. I finally got a chance to play with your dataset. There's a lot going on.

First, some problems that are unrelated to potential bugs:

(1) In one of the constraints, a fossil is referred to as `Bradoponera` rather than as `Bradoponera_wunderlichi`.

(2) Since the removal probability `r` is set to 1 inside `dnBDSTP`, the script triggers the warning implemented in PR #440. If you are dealing with fossils and want ancestors to be sampled, it needs to be set to 0 instead.

(3) The script `Leptanillinae_FBDP_subsets_con-tau.rev` (which uses both monophyly constraints and a backbone constraint) indeed doesn't work and cannot possibly work, because the backbone topology violates the monophyly constraints. For example, the file `clade_Formicinae.rev` tries to enforce the monophyly of the following set of taxa:

- "Kyromyrma_neffi" [fossil]
- "Formica_paralugubris"
- "Formica_sanguinea"
- "Camponotus_fellah"
- "Camponotus_floridanus"
- "Polyrhachis_dives"
- "Plagiolepis_pygmaea"
- "Paratrechina_longicornis"
- "Oecophylla_smaragdina"
- "Myrmecocystus_mimicus",
- "Myrmelachista_zeledoni"
- "Lasius_flavus"
- "Anoplolepis_gracilipes"

However, the backbone (`a_posteriori_topology.txt`) requires that the least inclusive clade containing both "Anoplolepis_gracilipes" and "Myrmelachista_zeledoni" also include "Nylanderia_fulva". As a result, no topology can possibly satisfy both constraints simultaneously. This might stem from confusion about how constraints work in RevBayes. A backbone constraint doesn't have to be exhaustive in terms of the included taxa (indeed, it makes the most sense to use it when it's not), but monophyly constraints do have to list included taxa exhaustively. It seems like you were trying to do it the other way around.

Initialization issues:

(4) The script `Leptanillinae_FBDP_subsets.rev`, which uses monophyly constraints but no backbone constraint, indeed fails to find a starting state with computable probability after 1000 tries.

**---------- This is a legitimate issue, but not necessarily a bug. ----------**

Finding viable initial states for very complex models is notoriously difficult; sometimes we have to get around the issue by providing one of our own – i.e., a starting tree. So let's see what happens if we do...

RevBayes bugs:

(5) I made the following changes (see the attached files; all file extensions changed to `.txt` for GitHub's sake):

- Added the 13 fossils to `a_posteriori_topology.txt` in random positions that are compatible with the monophyly constraints;
- Time-scaled the tree using treePL (with the fossils serving as calibrations);
- Fixed two of the constraints to make them compatible with the tree (`clade_Dorylinae.rev`: did not include "Cerapachys_jacobsoni"; `clade_Formicinae.rev`: did not include "Nylanderia_fulva");
- Expanded zero-length stratigraphic age ranges in `Matrix_E_taxa.tsv` a little (e.g., instead of the `min_age` and `max_age` coinciding for "Kyromyrma_neffi" at 99 Ma, I set the values to 98.995 and 99.005 Ma, respectively).
- Changed the script to use the modified tree as a starting tree rather than a backbone constraint

This is enough to get the analysis running in v1.2.3 and without monophyly constraints. However, the analysis still won't find a viable initial state when the constraints are specified. That shouldn't happen: if the starting tree is good enough for `dnBDSTP` and if it satisfies all the monophyly constraints (which it does; I checked), it should be good enough for `dnConstrainedTopology` as well.

**---------- This looks like a bug. ----------**

Moreover, in v1.2.4, the analysis won't even run without constraints, because one part of PR #399 (commit 4d29f9a) broke a functionality I previously introduced in PR #386.

**---------- This is definitely a bug. ----------**

[Leptanillinae_FBDP_subsets_starting_tree.txt](https://github.com/user-attachments/files/15934698/Leptanillinae_FBDP_subsets_starting_tree.txt)
[clade_Dorylinae_revised.txt](https://github.com/user-attachments/files/15934703/clade_Dorylinae_revised.txt)
[clade_Formicinae_revised.txt](https://github.com/user-attachments/files/15934706/clade_Formicinae_revised.txt)
[Matrix_E_taxa_revised.txt](https://github.com/user-attachments/files/15934711/Matrix_E_taxa_revised.txt)
[starting_tree.txt](https://github.com/user-attachments/files/15934712/starting_tree.txt)

**Comment by ZGriebenow** [comment]
@davidcerny Greetings David, well, that's quite embarrassing: the omission of those two terminals from the clade constraints was a clerical error on my part, and I mistakenly thought that I had proofread for such mistakes.

One point of clarification:  when I implemented the analysis in v. 1.2.2, the discrepancy between the .tsv file and clade_Proceratiinae.rev was not thrown as an error before the MCMC was instantiated, hence why I had not noticed the issue. My prior experience with v. 1.2.2 and previous versions, though, is that such a discrepancy would prevent the analysis from proceeding. Is that not standard behavior?

Thanks for all of your efforts with this, and I sincerely apologize for my ineffective proofreading.

**Comment by davidcerny** [comment]
Hi @ZGriebenow, there is no reason to apologize! Your issue still seems to involve an actual RevBayes bug, and even if it didn't, there's nothing wrong with asking for help. :)

> One point of clarification: when I implemented the analysis in v. 1.2.2, the discrepancy between the .tsv file and clade_Proceratiinae.rev was not thrown as an error before the MCMC was instantiated, hence why I had not noticed the issue. My prior experience with v. 1.2.2 and previous versions, though, is that such a discrepancy would prevent the analysis from proceeding. Is that not standard behavior?

Throwing an error definitely is the standard behavior in that situation, and that's exactly what happens when I try to run the script you provided here in v1.2.2:

```
> source("/Users/David/Downloads/bug-report_122_docker/Leptanillinae_FBDP_subsets.rev")
   Processing file "/Users/David/Downloads/bug-report_122_docker/Leptanillinae_FBDP_subsets.rev"
   Successfully read one character matrix from file 'data/sorted_alignment_42genes_part1-out.nex'
   Successfully read one character matrix from file 'data/sorted_alignment_42genes_part2-out.nex'
   Processing file "clade_constraints/clade_Apidae.rev"
   Processing of file "clade_constraints/clade_Apidae.rev" completed
   Processing file "clade_constraints/clade_Apoidea.rev"
   Processing of file "clade_constraints/clade_Apoidea.rev" completed
   Processing file "clade_constraints/clade_Dolichoderinae.rev"
   Processing of file "clade_constraints/clade_Dolichoderinae.rev" completed
   Processing file "clade_constraints/clade_Dorylinae.rev"
   Processing of file "clade_constraints/clade_Dorylinae.rev" completed
   Processing file "clade_constraints/clade_Ectatomminae.rev"
   Processing of file "clade_constraints/clade_Ectatomminae.rev" completed
   Processing file "clade_constraints/clade_Formicinae.rev"
   Processing of file "clade_constraints/clade_Formicinae.rev" completed
   Processing file "clade_constraints/clade_Halictidae.rev"
   Processing of file "clade_constraints/clade_Halictidae.rev" completed
   Processing file "clade_constraints/clade_Myrmeciinae.rev"
   Processing of file "clade_constraints/clade_Myrmeciinae.rev" completed
   Processing file "clade_constraints/clade_Myrmicinae.rev"
   Processing of file "clade_constraints/clade_Myrmicinae.rev" completed
   Processing file "clade_constraints/clade_Ponerinae.rev"
   Processing of file "clade_constraints/clade_Ponerinae.rev" completed
   Processing file "clade_constraints/clade_Proceratiinae.rev"
   Processing of file "clade_constraints/clade_Proceratiinae.rev" completed
   Processing file "clade_constraints/clade_Pseudomyrmecinae.rev"
   Processing of file "clade_constraints/clade_Pseudomyrmecinae.rev" completed
   Processing file "clade_constraints/clade_Scolioidea.rev"
   Processing of file "clade_constraints/clade_Scolioidea.rev" completed
   Error:	Could not find taxon with name 'Bradoponera'.
   Error:	Problem processing line 104 in file "/Users/David/Downloads/bug-report_122_docker/Leptanillinae_FBDP_subsets.rev"
```

Could it be that you fixed the `Bradoponera`/`Bradoponera_wunderlichi` naming issue at some point, and what you uploaded here is an older version of your files from before that?

**Comment by davidcerny** [comment]
> This is enough to get the analysis running in v1.2.3 and without monophyly constraints. However, the analysis still won't find a viable initial state when the constraints are specified.

Okay, so I figured out what is happening here:

1. If an `initialTree` is only specified in the base distribution (`dnBDSTP`) but not in `dnConstrainedTopology`, the analysis ignores it, proceeds to try to find a viable initial state on its own, and fails;
2. If an `initialTree` is only specified in `dnConstrainedTopology` but not in the base distribution (`dnBDSTP`), the problem described in issue #354 re-emerges: the initial tree resets the minimum and maximum age of every fossil to 0, thus placing them outside the ranges from which their ages are supposed to be drawn;
3. If an `initialTree` is specified both in `dnConstrainedTopology` and in the base distribution (`dnBDSTP`), the problem described in (2) still occurs, because the later use of the `initialTree` (in `dnConstrainedTopology`, which doesn't ensure its compatibility with the specified fossil ages) overwrites its earlier use (in the base distribution).

The solution would be to check the `initialTree` of `dnConstrainedTopology` for the presence of fossils, and if any are found, run `TreeUtilities::startingTreeInitializer()` on it. I'll open a PR to implement this.

**Comment by davidcerny** [comment]
Okay @ZGriebenow, with the changes I've made to `dnConstrainedTopology` on [this new branch](https://github.com/revbayes/revbayes/tree/use-starting-tree), your analysis will run as intended (with fossil ages sampled from the corresponding stratigraphic ranges and with monophyly constraints) as long as a compatible starting tree is provided. Here is the script I used to get it running: it's very similar to the one from my previous comment, except that it deals more elegantly with the fact that most of your fossils are associated with age ranges (which you wish to sample from) but some have fixed point ages.

If you are able to use RevBayes outside of Docker, you can compile the code from my new branch and give it a try.

[Leptanillinae_FBDP_subsets.txt](https://github.com/user-attachments/files/15962963/Leptanillinae_FBDP_subsets.txt)

**Comment by ZGriebenow** [comment]
Thanks David, I'll discuss with my adviser tomorrow.

Regards, Zach
________________________________

**Comment by davidcerny** [comment]
So it seems that on the current version of the development branch (fe68484), the corrected script I attached to my last comment (`Leptanillinae_FBDP_subsets.txt`) runs just fine both with and without a user-specified initial tree. Between #453, #480, and #481, any issues which originally prevented the analysis from running (and which were unrelated to problems with the underlying data, like clashing constraints or incorrect taxon names) have apparently been fixed. Closing this.

**Comment by ZGriebenow** [comment]
Thanks very much, David! Am slowly learning a new cluster on which to run RevBayes and am preoccupied with a lot of other matters, so have not been able to try this script with the latest iteration of the development branch yet.

Regards, Zach
________________________________
